### ISSUE TITLE
default.gif?

### ISSUE THREAD

**Issue by asrafaiz7** [pavitrakumar78/Python-OpenCV-Paint#1]
what is default.gif in line 159 . what image is that?

**Comment by pavitrakumar78** [comment]
@asrafaiz7 When I was programming it, I think I was planning to start the tkinter application with a custom logo. I just checked the local files, the default.gif is just a blank image. So, it can just be commented out. But, beware that the program might not work properly right now because there has been a lot of changes in the cv2 library and it might affect the object detection mechanism used in this code.
